# Generated by Django 3.0.8 on 2020-09-23 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('author', models.CharField(default='', max_length=100, verbose_name='作者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
