# Generated by Django 3.0.8 on 2020-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='content',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='内容'),
        ),
    ]
