# Generated by Django 3.0.8 on 2020-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0002_auto_20200923_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
