# Generated by Django 3.0.8 on 2020-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0003_auto_20200923_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='image_url',
            field=models.URLField(default='', verbose_name='图片地址'),
        ),
    ]
