# Generated by Django 3.0.8 on 2020-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0004_quotations_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='图片地址'),
        ),
    ]
