# Generated by Django 3.0.8 on 2020-12-21 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0005_auto_20201130_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationsVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qv_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('votes', models.IntegerField(blank=True, null=True, verbose_name='图片地址')),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fhc.Quotations', verbose_name='语录')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
