# Generated by Django 3.0.8 on 2020-12-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0006_quotationsvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsvote',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fhc.Quotations', unique=True, verbose_name='语录'),
        ),
    ]
