# Generated by Django 3.0.8 on 2020-12-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0007_auto_20201221_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsvote',
            name='quotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fhc.Quotations', verbose_name='语录'),
        ),
    ]
