# Generated by Django 3.0.8 on 2020-12-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhc', '0008_auto_20201221_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsvote',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fhc.Quotations', verbose_name='语录'),
        ),
        migrations.AlterField(
            model_name='quotationsvote',
            name='votes',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='票数'),
        ),
    ]
