# Generated by Django 3.0.8 on 2020-07-20 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosernopic',
            options={'ordering': ['id'], 'verbose_name': 'Coser资源', 'verbose_name_plural': 'Coser资源'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_media',
        ),
        migrations.CreateModel(
            name='CoserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, unique=True, verbose_name='用户名')),
                ('social_media', models.ManyToManyField(blank=True, to='common.SocialMedia', verbose_name='社交平台')),
            ],
        ),
        migrations.AlterField(
            model_name='cosernopic',
            name='coser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.CoserInfo', verbose_name='coser'),
        ),
    ]
