# Generated by Django 3.0.8 on 2020-07-20 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200720_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coserinfo',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='url',
        ),
        migrations.CreateModel(
            name='CoserSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='社交软件地址')),
                ('coser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.CoserInfo', verbose_name='coser')),
                ('social_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.SocialMedia', verbose_name='social_media')),
            ],
            options={
                'verbose_name': 'coser社交平台关系',
                'verbose_name_plural': 'coser社交平台关系',
                'ordering': ['id'],
            },
        ),
    ]
