# Generated by Django 3.0.8 on 2020-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200720_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='coserinfo',
            name='name_en',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='英文名'),
        ),
    ]
