# Generated by Django 3.0.8 on 2020-10-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='common.Menu', verbose_name='菜单'),
        ),
    ]
