# Generated by Django 3.2.13 on 2022-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_role_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
