# Generated by Django 3.0.8 on 2021-04-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hero_id', models.IntegerField(blank=True, null=True, verbose_name='英雄id')),
                ('hero_name', models.CharField(default='', max_length=100, verbose_name='英雄名称')),
                ('localized_name', models.CharField(default='', max_length=100, verbose_name='本地英雄名称')),
                ('avatar_url', models.URLField(blank=True, default='', null=True, verbose_name='头像地址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
