# Generated by Django 3.0.8 on 2021-04-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heros',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='heros',
            name='modify_time',
        ),
    ]
