# Generated by Django 3.0.8 on 2021-06-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankmodel',
            name='is_show',
        ),
    ]
