# Generated by Django 3.0.8 on 2021-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0002_remove_rankmodel_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankmodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
