# Generated by Django 3.0.8 on 2021-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0002_auto_20210426_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='heros',
            name='position_type',
            field=models.CharField(blank=True, choices=[('1', '力量'), ('2', '敏捷'), ('3', '智力')], default='', max_length=30, verbose_name='分发类型'),
        ),
    ]
