# Generated by Django 3.0.8 on 2021-08-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0003_rankmodel_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotaItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='物品id')),
                ('item_name', models.CharField(default='', max_length=100, verbose_name='物品名称')),
                ('localized_name', models.CharField(default='', max_length=100, verbose_name='本地物品名称')),
                ('item_url', models.URLField(blank=True, default='', null=True, verbose_name='图片地址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
