# Generated by Django 3.0.8 on 2022-01-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0004_dotaitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchdata',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gametime', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'matchdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matchlist',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('match_name', models.CharField(max_length=100)),
                ('match_title', models.CharField(max_length=100)),
                ('teama', models.CharField(db_column='teamA', max_length=100)),
                ('teamb', models.CharField(db_column='teamB', max_length=100)),
                ('match_status', models.CharField(max_length=100)),
                ('match_date', models.CharField(max_length=100)),
                ('gametime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matchlist',
                'managed': False,
            },
        ),
    ]
