# Generated by Django 3.0.8 on 2021-03-04 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='', max_length=20, unique=True, verbose_name='壁纸名')),
                ('full_hd_url', models.URLField(blank=True, null=True, unique=True, verbose_name='1080 地址')),
                ('ultra_hd_url', models.URLField(blank=True, null=True, unique=True, verbose_name='4k 地址')),
            ],
        ),
    ]
