# Generated by Django 3.0.8 on 2022-01-02 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0005_auto_20210316_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag_name', models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='标签名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='tags',
            field=models.ManyToManyField(to='wallpaper.ImageTag', verbose_name='标签'),
        ),
    ]
