# Generated by Django 3.0.8 on 2022-01-03 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_auto_20220102_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category_name', models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='类别')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='aperture',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='光圈'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='focal_length',
            field=models.CharField(default='', max_length=50, verbose_name='焦距'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='iso',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='iso'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='地点'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='rate',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='评级'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='shutter',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='快门'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='des',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('width', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='宽')),
                ('height', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='高')),
                ('cdn_url', models.URLField(blank=True, default='', null=True, verbose_name='资源地址')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.WallPaper', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='categories',
            field=models.ManyToManyField(to='wallpaper.ImageCategory', verbose_name='类别'),
        ),
    ]
