# Generated by Django 3.0.8 on 2022-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_auto_20220103_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='equipment',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='器材'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评级'),
        ),
    ]
