# Generated by Django 3.0.8 on 2022-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0009_wallpaper_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesize',
            name='type',
            field=models.CharField(blank=True, choices=[(1, 'origin'), (2, '4k'), (3, 'thumbnail')], default=1, max_length=50, verbose_name='图片类型'),
        ),
    ]
