# Generated by Django 3.0.8 on 2022-01-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0010_imagesize_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='器材名称')),
                ('brand', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品牌名称')),
                ('type', models.CharField(blank=True, choices=[(1, 'camera'), (2, 'lens'), (3, 'phone'), (4, 'drone')], default=1, max_length=50, verbose_name='器材类型')),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='equipments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.Equipment', verbose_name='设备'),
        ),
    ]
