# Generated by Django 3.0.8 on 2022-01-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0012_auto_20220115_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='wallpaper',
            name='lens',
        ),
    ]
