# Generated by Django 3.0.8 on 2022-01-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0013_auto_20220115_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='is_shown',
            field=models.CharField(default=1, max_length=1, verbose_name='是否展示'),
        ),
    ]
