# Generated by Django 3.0.8 on 2022-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0014_wallpaper_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='shooting_date',
            field=models.CharField(default='', max_length=50, verbose_name='拍摄日期'),
        ),
    ]
