# Generated by Django 3.0.8 on 2022-05-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0015_wallpaper_shooting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='评论人')),
                ('e_mail_address', models.URLField(blank=True, default=None, null=True, verbose_name='邮箱地址')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='评论')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.WallPaper')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_parent', to='wallpaper.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
