# Generated by Django 3.0.8 on 2022-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='verify_status',
            field=models.CharField(choices=[(0, '未审核'), (1, '已审核')], default=0, max_length=1, verbose_name='审核状态'),
        ),
    ]
