# Generated by Django 3.0.8 on 2022-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0017_comment_verify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='rate',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='评级'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='shooting_date',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='拍摄日期'),
        ),
    ]
