# Generated by Django 3.2.13 on 2022-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0018_auto_20220528_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesize',
            name='color_range',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='主色值'),
        ),
    ]
